baseURL = 'https://aituyaa.com/'
languageCode = 'zh-cn'
title = 'çˆ±æ¶‚é¸¦å•Š'

# å¯ç”¨ä¸»é¢˜
theme = 'virgo'

hasCJKLanguage = true
summaryLength = 80
paginate = 10000
enableGitInfo = true
timeZone = 'Asia/Shanghai'

ignoreFiles = ['content/.obsidian/*', 'content/__snippets/*', 'content/_mine/*']

[params]
    dark = false                            # é»˜è®¤å¼€å¯æš—è‰²ä¸»é¢˜
    author = 'Jack'
    slogan = 'Life should be interesting.'  # 'Life is just a joker.'
    startDate = 2016                        # 'Copyright Â© 2016 - now'
    # æ¿€æ´»é¡µé¢åŠ è½½æ—¶çš„è¿‡æ¸¡åŠ¨ç”»
    hasActiveAnimate = true
    # æ¿€æ´»é¡µé¢æµ®åŠ¨ç›’å­åŠ¨ç”»
    # hasActiveFloatingBox = true
    # æ–‡ç« é¡µæ˜¯å¦æ˜¾ç¤ºå…¶ç›¸å…³ç³»åˆ—æ–‡ç« ï¼ˆé¡µé¢å·¦ä¾§åŒºåŸŸï¼‰
    isShowRelativePosts = true
    # å¯¼èˆªé¡µå³ä¾§æ˜¯å¦æ˜¾ç¤ºè¿·ä½ å¿…åº”æœç´¢
    isShowMinishipBoxOfNav = true
    # å¯¼èˆªé¡µæ˜¯å¦æ˜¾ç¤ºé¡¶éƒ¨æœç´¢åŒºåŸŸ
    isShowShipBoxOfNav = true
    # å¯¼èˆªé¡µæ˜¯å¦æ˜¾ç¤ºç«™å†…æœç´¢ï¼ˆç«™å†…æ–‡ç« å†…å®¹æ£€ç´¢ï¼‰
    # ... æ¡Œé¢ç«¯æ¯å¤©è‡ªåŠ¨æ›´æ–°ç«™å†…æ–‡ç« ç¼“å­˜
    # ... ç§»åŠ¨ç«¯æ¯æœˆè‡ªåŠ¨æ›´æ–°ç«™å†…æ–‡ç« ç¼“å­˜
    # ... å¯ä»¥ç‚¹å·¦ä¾§å›¾æ ‡å¼ºåˆ¶æ›´æ–°æœ€æ–°ç¼“å­˜
    isShowLocalSearch = true
    # å¯¼èˆªé¡µæ˜¯å¦æ˜¾ç¤ºæœ€è¿‘æ–‡ç« åˆ—è¡¨
    isShowRecentPostsOfNav = true

    # æ¿€æ´» cool æ¨¡å¼ï¼Œé…·çˆ½ä½†æ˜¯æ¶ˆè€—èµ„æºä¹Ÿæ›´å¤šï¼Œ
    # æµè§ˆå™¨æœ‰ç¼“å­˜ï¼Œæ›´æ¢åå¼ºåˆ¶é¡µé¢åˆ·æ–°ï¼ˆå¿«æ·é”®ä¸º Ctrl+Shift+Rï¼‰ä¸€ä¸‹æˆ–é‡å¯æœ¬åœ°æœåŠ¡å³å¯ï¼Œ
    # ------------------
    # <æ›´æ–°> ç°åœ¨å¯ä»¥ç›´æ¥åœ¨è¿™é‡Œä¿®æ”¹èƒŒæ™¯å£çº¸å¹¶è°ƒæ•´å£çº¸é®ç½©é€æ˜åº¦
    # - coolBackground æ–‡ä»¶ä½äº `/static/imgs/bg` æ–‡ä»¶å¤¹ä¸­ï¼Œé»˜è®¤ä¸º `default.jpg`
    # - coolOpacity é»˜è®¤ä¸º 0.81 ï¼ŒèƒŒæ™¯è‰²å½©é€æ˜åº¦ï¼Œåœ¨ 0 ~ 1 ä¹‹é—´
    # - coolSaturate é»˜è®¤ä¸º 180% ï¼ŒèƒŒæ™¯è‰²å½©é¥±å’Œåº¦ï¼Œåœ¨ 0% ~ 200% ä¹‹é—´
    # - coolBlur é»˜è®¤ä¸º 6px ï¼ŒèƒŒæ™¯è‰²å½©æ¨¡ç³Šåº¦ï¼Œæ•°å€¼è¶Šå¤§è¶Šæ¨¡ç³Š
    hasActiveCool = true
    coolBackground = 'color.jpg'
    coolOpacity = 0.69 # 0.86
    coolSaturate = '180%'
    coolBlur = '6px'
    
    # é¦–é¡µå›¾ç‰‡/æ–‡å­—
    [params.img]
        # å†…ç½®é»˜è®¤ä¸º `cat.svg â€¦â€¦`ï¼Œå½“ç„¶ä½ å¯ä»¥
        # æŠŠè‡ªå·±å–œæ¬¢å›¾ç‰‡æ”¾åœ¨ `static/imgs/` ç›®å½•ä¸­ï¼Œå¹¶åœ¨ `src` å¼•ç”¨å®ƒ,
        # âŒ ä½ è¿˜å¯ä»¥é€šè¿‡ `width` è°ƒæ•´å¼•å…¥å›¾ç‰‡çš„æ˜¾ç¤ºå¤§å°ï¼Œ
        # âŒ å¦‚æœï¼Œå°† `width` è®¾ç½®ä¸º '' æˆ– 0 ï¼Œ
        # âŒ å°†é»˜è®¤ä½¿ç”¨å›¾ç‰‡è‡ªèº«åˆ†è¾¨ç‡å°ºå¯¸
        # âŒ width = 90
        # ğŸ”” å›¾æ ‡ç”¨é€”å‘ç”Ÿå˜åŒ–ï¼Œä¸å†æ”¯æŒæ­¤å¤„è®¾ç½®å°ºå¯¸ï¼Œä½†
        # æ–°å¢æ”¯æŒè®¾ç½®èƒŒæ™¯è‰²ï¼Œ
        # å°† background è®¾ç½®ä¸º ''ï¼Œé»˜è®¤ä¸º `#000`
        # ï¼ ä¸ºä¿è¯æ˜¾ç¤ºæ•ˆæœï¼Œå»ºè®®é€‰ç”¨ 1ï¼š1 æ¯”ä¾‹å›¾ç‰‡
        # src = 'cat.svg'
        src = 'us-cartoon--mustache.png'
        background = '#0003'
        # ä¸ºè¯¥å›¾ç‰‡é™„åŠ ä¸€ä¸ªç‚¹å‡»é“¾æ¥åŠŸèƒ½ï¼Œç¼ºçœä¸º `/about`ï¼Œå½“ç„¶
        # ä½ ä¹Ÿå¯ä»¥å®šä¹‰ä¸ºä»»ä½•ä½ ç›¸è¦çš„è¶…é“¾æ¥
        link = '/about'

    [params.contact]
        icp = 'å°†å–œæ¬¢çš„ä¸€åˆ‡ç•™åœ¨èº«è¾¹ï¼Œè¿™ä¾¿æ˜¯åŠªåŠ›çš„æ„ä¹‰'                  # å¤‡æ¡ˆå·ï¼Œå¦‚æœä½ ä¸æƒ³æ˜¾ç¤ºï¼Œè®¾ç½®ä¸º '' ç©ºå³å¯
        icplink = '/about'                                              # å¤‡æ¡ˆé“¾æ¥
        beian = ''                                                      # å…¬å®‰å¤‡æ¡ˆï¼Œå¦‚æœä½ ä¸æƒ³æ˜¾ç¤ºï¼Œè®¾ç½®ä¸º '' ç©ºå³å¯
        beiancode = ''                                                  # å…¬å®‰å¤‡æ¡ˆè¯†åˆ«ç 
        github_user = 'loveminimal'                                     # Github ç”¨æˆ·åï¼Œå¯¼èˆªé¡µ github å°ç»„ä»¶ä½¿ç”¨
        # wechat = 'imgs/bg/wechat.jpg'                                 # å¾®ä¿¡äºŒç»´ç åœ°å€
        weibo = 'https://weibo.com/u/6867589681'
        zhihu = 'https://www.zhihu.com/people/loveminimal'
        jianshu = 'https://www.jianshu.com/u/eebcc2974936'
        email = 'loveminimal@163.com'
        github = 'https://github.com/loveminimal'
        bilibili = 'https://space.bilibili.com/11608450'
        douyin = 'https://www.douyin.com/user/self'
        xiaohongshu = 'https://www.xiaohongshu.com/user/profile/60004c750000000001002065'
        # reddit = 'https://www.reddit.com/user/aituyaa'
        twitter = 'https://twitter.com/aituyaa'
        # mastodon = 'https://mastodon.social/@loveminimal'
        instagram = 'https://www.instagram.com/aituyaa'
        youtube = 'https://www.youtube.com/@aituyaa'
        telegram = 'https://web.telegram.org/k/#@aituyaa'	# 'https://t.me/aituyaa'
        # discord = 'https://discord.com/channels/@me'

        [params.contact.config]
            color = '#696969'                         # å›¾æ ‡é¢œè‰²ï¼Œé»˜è®¤ä¸ºæµ…ç°è‰²
            slogan = ''                               # è”ç³»æ ‡è¯­ï¼Œä¸æƒ³æ˜¾ç¤ºï¼Œå¯ä»¥ç½®ç©º
            # isShowNavLink = true                      # æ˜¯å¦åœ¨è”ç³»æ å·¦ä¾§æ˜¾ç¤ºå¿«æ·å¯¼èˆªé“¾æ¥ï¼ˆPSï¼šç«™ç‚¹é¦–é¡µæ€»ä¼šæ˜¾ç¤ºï¼‰
            target = '_self'                          # å®šä¹‰å·¦ä¾§å¿«æ·å¯¼èˆªé“¾æ¥æ‰“å¼€æ–¹å¼ï¼Œ_blank åœ¨æ–°æ ‡ç­¾é¡µ _self åœ¨å½“å‰æ ‡ç­¾é¡µ
            ship = ''                                 # è”ç³»æ  icon ï¼Œå…è®¸è‡ªå®šä¹‰è¯¥å›¾æ ‡é“¾æ¥ï¼ˆ/ship ä¸ºå¤–é“¾çš„ä¸ªäººå®šåˆ¶åŒ–æœç´¢é¡µï¼‰ï¼›éšè—ï¼Œè®¾ç½®ä¸º '' ç©ºå³å¯

    # https://utteranc.es/
    # åœ¨å¼€å‘ç¯å¢ƒä¸‹ï¼ˆhttp://localhost:1313/ï¼‰ï¼Œä¸å†å¯ç”¨è¯„è®ºæ’ä»¶ï¼Œ
    # å¦‚æœæƒ³åœ¨å¼€å‘ç¯å¢ƒä¸‹å¯ç”¨å®ƒï¼Œä¿®æ”¹æœåŠ¡ç«¯å£å³å¯ï¼Œå¦‚ä¸‹
    # hugo server -p=1314
    [params.utterances]
        active = false                            # æ˜¯å¦å¯ç”¨è¯„è®ºæ’ä»¶
        repo = "loveminimal/comment"              # è¾“å…¥ä½ çš„ä»“åº“åç§°
        issueTerm = "pathname"
        theme = "github-light"
        crossorigin = "anonymous"

    # åœ¨å¼€å‘ç¯å¢ƒä¸‹ï¼ˆhttp://localhost:1313/ï¼‰ï¼Œä¸å†å¯ç”¨è¯„è®ºæ’ä»¶ï¼Œ
    # å¦‚æœæƒ³åœ¨å¼€å‘ç¯å¢ƒä¸‹å¯ç”¨å®ƒï¼Œä¿®æ”¹æœåŠ¡ç«¯å£å³å¯ï¼Œå¦‚ä¸‹
    # hugo server -p=1314
    # ---------
    # åœ¨ https://giscus.app/ ä¸­ï¼Œé€‰æ‹©é…ç½®åä¼šè‡ªåŠ¨ç”Ÿæˆï¼Œå¦‚ data-*
    # é»˜è®¤å¼€å¯ data-loading="lazy"
    [params.giscus]
        active = true                             # æ˜¯å¦å¯ç”¨è¯„è®ºæ’ä»¶
        repo = "loveminimal/comment"              # è¾“å…¥ä½ çš„ä»“åº“åç§°
        repoId = "R_kgDOJNJQ8g"
        category="General"
        categoryId="DIC_kwDOJNJQ8s4CYl0m"
        mapping = "title"
        inputPosition = "bottom"
        theme = "noborder_light"
        crossorigin = "anonymous"
        lang = "zh-CN"

# ä»¥ä¸‹ä¸º Markdown è§£ææ“çš„ä¸€äº›è®¾ç½®ï¼Œ
# å»ºè®®ä¿æŒä¸å˜
[markup]
    [markup.asciidocExt]
        preserveTOC = true
    [markup.highlight]
        # ä»£ç å—æ˜¾ç¤ºé£æ ¼ã€è¡Œå·æ˜¾ç¤º
        style = "github"
        lineNos = true
    [markup.tableOfContents]
        endLevel = 4
        ordered = false
        startLevel = 2
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
