baseURL = 'https://walkssi.com/'
languageCode = 'zh-cn'
title = 'Walkssi'

# å¯ç”¨ä¸»é¢˜
theme = 'virgo'

hasCJKLanguage = true
summaryLength = 80
paginate = 10000
enableGitInfo = true

[params]
    author = 'Jack'
    slogan = 'Life should be interesting.' # 'Life is just a joker.'

    # æ¿€æ´»é¡µé¢åŠ è½½æ—¶çš„è¿‡æ¸¡åŠ¨ç”»
    hasActiveAnimate = true

    # æ¿€æ´» cool æ¨¡å¼ï¼Œé…·çˆ½ä½†æ˜¯æ¶ˆè€—èµ„æºä¹Ÿæ›´å¤šï¼Œ
    # å¦‚æœæƒ³æ›´æ¢é¡µé¢èƒŒæ™¯ï¼Œåªéœ€è¦å°†å›¾ç‰‡å‘½åä¸º `default.jpg` åï¼Œç½®äº `/static/imgs/bg` æ–‡ä»¶å¤¹ä¸­å³å¯ï¼Œ
    # æµè§ˆå™¨æœ‰ç¼“å­˜ï¼Œæ›´æ¢åå¼ºåˆ¶é¡µé¢åˆ·æ–°ï¼ˆå¿«æ·é”®ä¸º Ctrl+Shift+Rï¼‰ä¸€ä¸‹å³å¯
    hasActiveCool = false
    
    # é¦–é¡µå›¾ç‰‡/æ–‡å­—
    [params.img]
        # å†…ç½®é»˜è®¤ä¸º `cat.svg â€¦â€¦`ï¼Œå½“ç„¶ä½ å¯ä»¥
        # æŠŠè‡ªå·±å–œæ¬¢å›¾ç‰‡æ”¾åœ¨ `static/imgs/` ç›®å½•ä¸­ï¼Œå¹¶åœ¨ `src` å¼•ç”¨å®ƒ,
        # âŒ ä½ è¿˜å¯ä»¥é€šè¿‡ `width` è°ƒæ•´å¼•å…¥å›¾ç‰‡çš„æ˜¾ç¤ºå¤§å°ï¼Œ
        # âŒ å¦‚æœï¼Œå°† `width` è®¾ç½®ä¸º '' æˆ– 0 ï¼Œ
        # âŒ å°†é»˜è®¤ä½¿ç”¨å›¾ç‰‡è‡ªèº«åˆ†è¾¨ç‡å°ºå¯¸
        # âŒ width = 90
        # ğŸ”” å›¾æ ‡ç”¨é€”å‘ç”Ÿå˜åŒ–ï¼Œä¸å†æ”¯æŒæ­¤å¤„è®¾ç½®å°ºå¯¸ï¼Œä½†
        # æ–°å¢æ”¯æŒè®¾ç½®èƒŒæ™¯è‰²ï¼Œ
        # å°† background è®¾ç½®ä¸º ''ï¼Œé»˜è®¤ä¸º `#000`
        # ï¼ ä¸ºä¿è¯æ˜¾ç¤ºæ•ˆæœï¼Œå»ºè®®é€‰ç”¨ 1ï¼š1 æ¯”ä¾‹å›¾ç‰‡
        # src = 'cat.svg'
        src = 'messi.png'
        background = '#0003'
        # ä¸ºè¯¥å›¾ç‰‡é™„åŠ ä¸€ä¸ªç‚¹å‡»é“¾æ¥åŠŸèƒ½ï¼Œç¼ºçœä¸º `/about`ï¼Œå½“ç„¶
        # ä½ ä¹Ÿå¯ä»¥å®šä¹‰ä¸ºä»»ä½•ä½ ç›¸è¦çš„è¶…é“¾æ¥
        link = '/about'

    [params.contact]
        icp = 'è±«ICPå¤‡2023017189å·-1'             # å¤‡æ¡ˆå·ï¼Œå¦‚æœä½ ä¸æƒ³æ˜¾ç¤ºï¼Œè®¾ç½®ä¸º '' ç©ºå³å¯
        icplink = '//beian.miit.gov.cn'           # å¤‡æ¡ˆé“¾æ¥
        beian = 'è±«å…¬ç½‘å®‰å¤‡ 41092802000242å·'      # å…¬å®‰å¤‡æ¡ˆï¼Œå¦‚æœä½ ä¸æƒ³æ˜¾ç¤ºï¼Œè®¾ç½®ä¸º '' ç©ºå³å¯
        beiancode = '41092802000242'             # å…¬å®‰å¤‡æ¡ˆè¯†åˆ«ç 
        weibo = '6867589681'                     # e.g. https://weibo.com/u/6867589681
        wechat = 'imgs/bg/wechat.jpg'            # å¾®ä¿¡äºŒç»´ç åœ°å€
        zhihu = 'loveminimal'                    # e.g. https://www.zhihu.com/people/loveminimal
        jianshu = 'eebcc2974936'                 # e.g. https://www.jianshu.com/u/eebcc2974936
        email = 'loveminimal@163.com'
        github = 'loveminimal'                   # e.g. https://github.com/loveminimal
        bilibili = '11608450'                    # e.g. https://space.bilibili.com/11608450
        douyin = 'self'                          # e.g. https://www.douyin.com/user/self
        xiaohongshu = '60004c750000000001002065' #e.g. https://www.xiaohongshu.com/user/profile/60004c750000000001002065
        twitter = 'loveminimal163'                 # e.g. https://twitter.com/loveminimal163
        facebook = 'loveminimal'               # e.g. https://facebook.com/loveminimal
        instagram = 'loveminimal163'            # e.g. https://www.instagram.com/loveminimal163
        youtube = 'walkssi'                     # e.g. https://www.youtube.com/@walkssi
        telegram = 'loveminimal'                # e.g. https://web.telegram.org/k/#@loveminimal
        color = '#696969'                        # å›¾æ ‡é¢œè‰²ï¼Œé»˜è®¤ä¸ºæµ…ç°è‰²
        slogan = ''               # è”ç³»æ ‡è¯­ï¼Œä¸æƒ³æ˜¾ç¤ºï¼Œå¯ä»¥ç½®ç©º

    # åœ¨å¼€å‘ç¯å¢ƒä¸‹ï¼ˆhttp://localhost:1313/ï¼‰ï¼Œä¸å†å¯ç”¨è¯„è®ºæ’ä»¶ï¼Œ
    # å¦‚æœæƒ³åœ¨å¼€å‘ç¯å¢ƒä¸‹å¯ç”¨å®ƒï¼Œä¿®æ”¹æœåŠ¡ç«¯å£å³å¯ï¼Œå¦‚ä¸‹
    # hugo server -p=1314
    [params.utterances]
        active = false                             # æ˜¯å¦å¯ç”¨è¯„è®ºæ’ä»¶
        repo = "loveminimal/comment"               # è¾“å…¥ä½ çš„ä»“åº“åç§°
        issueTerm = "pathname"
        theme = "github-light"
        crossorigin = "anonymous"

    # åœ¨å¼€å‘ç¯å¢ƒä¸‹ï¼ˆhttp://localhost:1313/ï¼‰ï¼Œä¸å†å¯ç”¨è¯„è®ºæ’ä»¶ï¼Œ
    # å¦‚æœæƒ³åœ¨å¼€å‘ç¯å¢ƒä¸‹å¯ç”¨å®ƒï¼Œä¿®æ”¹æœåŠ¡ç«¯å£å³å¯ï¼Œå¦‚ä¸‹
    # hugo server -p=1314
    # ---------
    # åœ¨ https://giscus.app/ ä¸­ï¼Œé€‰æ‹©é…ç½®åä¼šè‡ªåŠ¨ç”Ÿæˆï¼Œå¦‚ data-*
    # é»˜è®¤å¼€å¯ data-loading="lazy"
    [params.giscus]
        active = true                             # æ˜¯å¦å¯ç”¨è¯„è®ºæ’ä»¶
        repo = "loveminimal/comment"               # è¾“å…¥ä½ çš„ä»“åº“åç§°
        repoId = "R_kgDOJNJQ8g"
        category="General"
        categoryId="DIC_kwDOJNJQ8s4CYl0m"
        mapping = "title"
        inputPosition = "bottom"
        theme = "noborder_light"
        crossorigin = "anonymous"
        lang = "zh-CN"

# ä»¥ä¸‹ä¸º Markdown è§£ææ“çš„ä¸€äº›è®¾ç½®ï¼Œ
# å»ºè®®ä¿æŒä¸å˜
[markup]
    [markup.asciidocExt]
        preserveTOC = true
    [markup.highlight]
        # ä»£ç å—æ˜¾ç¤ºé£æ ¼ã€è¡Œå·æ˜¾ç¤º
        style = "github"
        lineNos = true
    [markup.tableOfContents]
        endLevel = 3
        ordered = false
        startLevel = 2
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
